repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
    # https://istio.io/latest/docs/setup/install/helm/
  - name: kiali
    url: https://kiali.org/helm-charts
    # https://kiali.io/docs/installation/installation-guide/install-with-helm/

releases:
  - name: istio-base
    namespace: istio-system
    createNamespace: true
    chart: istio/base
  - name: istiod
    namespace: istio-system
    createNamespace: true
    chart: istio/istiod
    values:
      - ./helm-values/istiod.yaml
  - name: kiali-operator
    namespace: kiali-operator
    createNamespace: true
    chart: kiali/kiali-operator
    values:
      - ./helm-values/kiali.yaml
