---
apiVersion: v1
kind: Service
metadata:
  name: backend1
  namespace: primary
spec:
  selector:
    app: backend1
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  namespace: primary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
        - name: nginx
          image: nginx:1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend2
  namespace: primary
spec:
  selector:
    app: backend2
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
  namespace: primary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
        - name: nginx
          image: nginx:1
          ports:
            - containerPort: 80
